"""Primary group for each cheat-sheets.org topic id.

Groups follow the README request (languages, databases, applications,
business processes, GNU/Linux commands, file formats, online data
services) plus clusters suggested by the site's own See also links
(Linux/Unix, Math, Java, Adobe, XML, ...).
"""

GROUPS = {
    "languages": {
        "title": "Languages",
        "description": "Programming languages and language runtimes.",
    },
    "databases": {
        "title": "Databases",
        "description": "SQL and NoSQL databases, query languages, and data-access APIs.",
    },
    "applications": {
        "title": "Applications",
        "description": "End-user applications, browsers, CMS, office, and mail.",
    },
    "business-processes": {
        "title": "Business processes",
        "description": "BPM/BPMN, BPEL, BI, modeling, and related process notations.",
    },
    "gnu-linux-commands": {
        "title": "GNU / Linux commands",
        "description": (
            "Unix/Linux command-line tools and shells (cat, less, awk, sed, ls, …), "
            "plus Linux/Unix overview sheets the site clusters via See also."
        ),
    },
    "file-formats": {
        "title": "File formats",
        "description": "Encodings, markup, document types, and file-extension references.",
    },
    "online-data-services": {
        "title": "Online data services",
        "description": "Hosted platforms, search, maps, mail, and social data services.",
    },
    "web": {
        "title": "Web",
        "description": "Web APIs, browsers' web stack, JS libraries, and HTTP-facing frameworks.",
    },
    "operating-systems": {
        "title": "Operating systems",
        "description": "Desktop/server OS families and distributions (See also: Linux, Unix).",
    },
    "mathematics-and-science": {
        "title": "Mathematics and science",
        "description": "Math, statistics, science, and scientific computing (See also: Math).",
    },
    "version-control": {
        "title": "Version control",
        "description": "Revision-control systems (See also: Git).",
    },
    "editors-and-ides": {
        "title": "Editors and IDEs",
        "description": "Text editors, IDEs, and related tooling.",
    },
    "networking-and-protocols": {
        "title": "Networking and protocols",
        "description": "Network protocols, mail, chat, and scanning tools.",
    },
    "cloud-and-devops": {
        "title": "Cloud and DevOps",
        "description": "Servers, containers, orchestration, CI, and infrastructure tools.",
    },
    "graphics-and-design": {
        "title": "Graphics and design",
        "description": "Graphics suites, drawing tools, and visual design (See also: Adobe).",
    },
    "frameworks-and-libraries": {
        "title": "Frameworks and libraries",
        "description": "Application frameworks, libraries, and language ecosystems.",
    },
    "security": {
        "title": "Security",
        "description": "Web and transport security references.",
    },
    "hardware-and-embedded": {
        "title": "Hardware and embedded",
        "description": "Hardware, embedded boards, and parallel compute APIs.",
    },
    "other": {
        "title": "Other",
        "description": "Topics that do not fit the groups above.",
    },
}

# topic id -> group key
PRIMARY = {
    # languages
    "Ada": "languages",
    "AssemblyLanguage": "languages",
    "C": "languages",
    "CSharp": "languages",
    "CPP": "languages",
    "Clojure": "languages",
    "Dart": "languages",
    "Delphi": "languages",
    "Erlang": "languages",
    "FSharp": "languages",
    "Fortran": "languages",
    "Golang": "languages",
    "Groovy": "languages",
    "Haskell": "languages",
    "HotSpot": "languages",
    "Java": "languages",
    "JavaScript": "languages",
    "Julia": "languages",
    "Kotlin": "languages",
    "Lisp": "languages",
    "Lua": "languages",
    "Objective-C": "languages",
    "Perl": "languages",
    "PHP": "languages",
    "Prolog": "languages",
    "Python": "languages",
    "R": "languages",
    "Rebol": "languages",
    "Ruby": "languages",
    "Rust": "languages",
    "Scala": "languages",
    "Solidity": "languages",
    "Swift": "languages",
    "TclTk": "languages",
    "TypeScript": "languages",
    "VBScript": "languages",
    "VisualBasic": "languages",
    "Verilog": "languages",
    "VHDL": "languages",
    "Languages": "languages",
    "DotNET": "languages",
    "Datalog": "languages",
    # databases
    "ADONET": "databases",
    "ApacheCassandra": "databases",
    "BerkeleyDB": "databases",
    "DB2": "databases",
    "db4o": "databases",
    "HBase": "databases",
    "Hibernate": "databases",
    "JavaPersistenceAPI": "databases",
    "JDBC": "databases",
    "MySQL": "databases",
    "Oracle": "databases",
    "PostgreSQL": "databases",
    "Redis": "databases",
    "SQL": "databases",
    "SQLServer": "databases",
    "SQLite": "databases",
    "Sybase": "databases",
    "Doctrine": "databases",
    "Hadoop": "databases",
    # applications
    "Android": "applications",
    "Blogger": "applications",
    "Drupal": "applications",
    "Firefox": "applications",
    "FirefoxAddOns": "applications",
    "Gmail": "applications",
    "GoogleChrome": "applications",
    "LotusDomino": "applications",
    "MicrosoftExcel": "applications",
    "MicrosoftOffice": "applications",
    "MicrosoftProject": "applications",
    "Thunderbird": "applications",
    "WordPress": "applications",
    "Freeware": "applications",
    "Quicksilver": "applications",
    "UnrealEngine": "applications",
    "vvvv": "applications",
    "Wikipedia": "applications",
    "SocialMedia": "applications",
    "Twitter": "applications",
    "Gift": "applications",
    "Guitar": "applications",
    "Music": "applications",
    "Camera": "applications",
    # business processes
    "BIRT": "business-processes",
    "BPEL": "business-processes",
    "BusinessProcessModeling": "business-processes",
    "DomainDrivenDesign": "business-processes",
    "DesignPattern": "business-processes",
    "UML": "business-processes",
    "MVVM": "business-processes",
    "EJB": "business-processes",
    # gnu / linux commands (and Linux/Unix cluster)
    "AWK": "gnu-linux-commands",
    "APT": "gnu-linux-commands",
    "chmod": "gnu-linux-commands",
    "Cron": "gnu-linux-commands",
    "Curl": "gnu-linux-commands",
    "Ed": "gnu-linux-commands",
    "less": "gnu-linux-commands",
    "Linux": "gnu-linux-commands",
    "Sed": "gnu-linux-commands",
    "Screen": "gnu-linux-commands",
    "ShellScript": "gnu-linux-commands",
    "Unix": "gnu-linux-commands",
    "rpm": "gnu-linux-commands",
    "GDB": "gnu-linux-commands",
    "Nano": "gnu-linux-commands",
    "OpenSSH": "gnu-linux-commands",
    # file formats
    "ASCII": "file-formats",
    "Characters": "file-formats",
    "Doctypes": "file-formats",
    "DOTlanguage": "file-formats",
    "DTD": "file-formats",
    "File": "file-formats",
    "Fonts": "file-formats",
    "HTML": "file-formats",
    "Image": "file-formats",
    "Markdown": "file-formats",
    "MathML": "file-formats",
    "Microformats": "file-formats",
    "MIME": "file-formats",
    "SVG": "file-formats",
    "TeX": "file-formats",
    "LaTeX": "file-formats",
    "Unicode": "file-formats",
    "XML": "file-formats",
    "XMLSchema": "file-formats",
    "XPath": "file-formats",
    "XSL": "file-formats",
    "XSLT": "file-formats",
    "XHTML": "file-formats",
    "VoiceXML": "file-formats",
    "Feed": "file-formats",
    "OpenGraph": "file-formats",
    "TLDs": "file-formats",
    "CSS": "file-formats",
    "Colour": "file-formats",
    "InternationalPhoneticAlphabet": "file-formats",
    # online data services
    "AmazonWebServices": "online-data-services",
    "Azure": "online-data-services",
    "CloudComputing": "online-data-services",
    "Google": "online-data-services",
    "GoogleAppEngine": "online-data-services",
    "GoogleMaps": "online-data-services",
    "OpenSearch": "online-data-services",
    # web
    "AJAX": "web",
    "ASP": "web",
    "Blueprint": "web",
    "DOM": "web",
    "GWT": "web",
    "htaccess": "web",
    "HTTP": "web",
    "JavaServerFaces": "web",
    "jQuery": "web",
    "JSP": "web",
    "MooTools": "web",
    "Nodejs": "web",
    "Prototype": "web",
    "REST": "web",
    "RichFaces": "web",
    "Selenium": "web",
    "SSI": "web",
    "WebGL": "web",
    "WebMatrix": "web",
    "Wicket": "web",
    "OnlyOne": "web",  # Zen Coding
    "mod_rewrite": "web",
    "mod_perl": "web",
    "OpenGL": "web",
    # operating systems
    "Debian": "operating-systems",
    "Fedora": "operating-systems",
    "Mac": "operating-systems",
    "OSX": "operating-systems",
    "RedHat": "operating-systems",
    "Solaris": "operating-systems",
    "Ubuntu": "operating-systems",
    "Windows": "operating-systems",
    "OpenVZ": "operating-systems",
    "WindowsPowerShell": "operating-systems",
    "WindowsCommunicationFoundation": "operating-systems",
    "WindowsPresentationFoundation": "operating-systems",
    # math and science
    "Algebra": "mathematics-and-science",
    "Astronomy": "mathematics-and-science",
    "BigO": "mathematics-and-science",
    "Calculus": "mathematics-and-science",
    "Chemistry": "mathematics-and-science",
    "ComputerScience": "mathematics-and-science",
    "Geometry": "mathematics-and-science",
    "Logic": "mathematics-and-science",
    "MachineLearning": "mathematics-and-science",
    "Maple": "mathematics-and-science",
    "Math": "mathematics-and-science",
    "Mathematica": "mathematics-and-science",
    "Mathomatic": "mathematics-and-science",
    "MATLAB": "mathematics-and-science",
    "Maxima": "mathematics-and-science",
    "NeuralNetwork": "mathematics-and-science",
    "Numbers": "mathematics-and-science",
    "PARIGP": "mathematics-and-science",
    "Physics": "mathematics-and-science",
    "ProbabilityTheory": "mathematics-and-science",
    "SageMath": "mathematics-and-science",
    "Science": "mathematics-and-science",
    "Statistics": "mathematics-and-science",
    "Trigonometry": "mathematics-and-science",
    # version control
    "Bazaar": "version-control",
    "CVS": "version-control",
    "Git": "version-control",
    "Perforce": "version-control",
    "SVN": "version-control",
    # editors and IDEs
    "Eclipse": "editors-and-ides",
    "Emacs": "editors-and-ides",
    "IntelliJIDEA": "editors-and-ides",
    "LaTeX-Suite": "editors-and-ides",
    "MicrosoftVisualStudio": "editors-and-ides",
    "NetBeans": "editors-and-ides",
    "Notepad++": "editors-and-ides",
    "orgmode": "editors-and-ides",
    "QtCreator": "editors-and-ides",
    "Qt": "frameworks-and-libraries",
    "Vi": "editors-and-ides",
    "Vim": "editors-and-ides",
    "ZenCoding": "web",
    "Countries": "other",
    "Vi": "editors-and-ides",
    "Xcode": "editors-and-ides",
    # networking
    "FTP": "networking-and-protocols",
    "HAProxy": "networking-and-protocols",
    "IRC": "networking-and-protocols",
    "NMAP": "networking-and-protocols",
    "Sendmail": "networking-and-protocols",
    "TCP": "networking-and-protocols",
    "TLS": "networking-and-protocols",
    # cloud / devops
    "Apache": "cloud-and-devops",
    "ApacheAnt": "cloud-and-devops",
    "ApacheCamel": "cloud-and-devops",
    "ApacheSolr": "cloud-and-devops",
    "Chef": "cloud-and-devops",
    "ContinuousIntegration": "cloud-and-devops",
    "Docker": "cloud-and-devops",
    "Jetty": "cloud-and-devops",
    "Kubernetes": "cloud-and-devops",
    "Lucene": "cloud-and-devops",
    "Maven": "cloud-and-devops",
    "Mule": "cloud-and-devops",
    "Nginx": "cloud-and-devops",
    "ServiceMix": "cloud-and-devops",
    "Virtualization": "cloud-and-devops",
    "VMware": "cloud-and-devops",
    "VeritasCluster": "cloud-and-devops",
    "ScalabilityHighAvailability": "cloud-and-devops",
    "JBoss": "cloud-and-devops",
    # graphics
    "Adobe": "graphics-and-design",
    "AdobeAcrobat": "graphics-and-design",
    "Gimp": "graphics-and-design",
    "Illustrator": "graphics-and-design",
    "InDesign": "graphics-and-design",
    "Inkscape": "graphics-and-design",
    "Photoshop": "graphics-and-design",
    "OpenSCAD": "graphics-and-design",
    # frameworks
    "Catalyst": "frameworks-and-libraries",
    "Cocoa": "frameworks-and-libraries",
    "ColdFusion": "frameworks-and-libraries",
    "Django": "frameworks-and-libraries",
    "FitNesse": "frameworks-and-libraries",
    "Grails": "frameworks-and-libraries",
    "Griffon": "frameworks-and-libraries",
    "JavaEE": "frameworks-and-libraries",
    "JUnit": "frameworks-and-libraries",
    "MFC": "frameworks-and-libraries",
    "OpenCL": "hardware-and-embedded",
    "OpenCV": "frameworks-and-libraries",
    "OpenMP": "hardware-and-embedded",
    "PHPFrameworks": "frameworks-and-libraries",
    "PlayFramework": "frameworks-and-libraries",
    "Quarkus": "frameworks-and-libraries",
    "RegularExpressions": "frameworks-and-libraries",
    "RubyRails": "frameworks-and-libraries",
    "Sandcastle": "frameworks-and-libraries",
    "Seam": "frameworks-and-libraries",
    "SpringFramework": "frameworks-and-libraries",
    "SpringRoo": "frameworks-and-libraries",
    "Symfony": "frameworks-and-libraries",
    "Tapestry": "frameworks-and-libraries",
    "TTCN-3": "frameworks-and-libraries",
    "Vaadin": "frameworks-and-libraries",
    # security
    "XSS": "security",
    # hardware
    "Arduino": "hardware-and-embedded",
    "Hardware": "hardware-and-embedded",
}

SKIP_IDS = {"Donate"}


def group_for(topic_id: str) -> str:
    if topic_id in SKIP_IDS:
        return "skip"
    return PRIMARY.get(topic_id, "other")
